server:
  port: 8208
  servlet:
    context-path: /trainee-user-management

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}

application:
  aws:
    cognito:
      user-pool-id: ${COGNITO_USER_POOL_ID}
      beta-participant-group: ${BETA_PARTICIPANT_GROUP}
    sns:
      user-account:
        update: ${USER_ACCOUNT_UPDATE_EVENT_TOPIC:}
    sqs:
      contact-details:
        updated: ${CONTACT_DETAILS_UPDATED_QUEUE:}
      request: ${REQUEST_QUEUE_URL:}
  environment: ${ENVIRONMENT:local}
  cache:
    key-prefix: UserManagement
    time-to-live: PT24H

spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      cloudwatch:
        namespace: TIS/Trainee/UserManagement
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ssl: ${REDIS_SSL:false}
    username: ${REDIS_USERNAME:default}
    password: ${REDIS_PASSWORD:password}
    timeout: 60000

profile:
  server:
    name: ${PROFILE_HOST:localhost}
    port: ${PROFILE_PORT:8082}

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}
