server:
  port: 8208
  servlet:
    context-path: /trainee-user-management

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}

application:
  aws:
    cognito:
      user-pool-id: ${COGNITO_USER_POOL_ID}
      dsp-consultant-group: ${COGNITO_DSP_CONSULTANT_GROUP}
    sqs:
      contact-details:
        updated: ${CONTACT_DETAILS_UPDATED_QUEUE:}
      request: ${REQUEST_QUEUE_URL:}
  environment: ${ENVIRONMENT:local}
  cache:
    key-prefix: UserManagement
    time-to-live: PT24H

cloud:
  aws:
    region:
      static: ${AWS_REGION}

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ssl:
      enabled: ${REDIS_SSL:false}
    username: ${REDIS_USERNAME:default}
    password: ${REDIS_PASSWORD:password}

profile:
  server:
    name: ${PROFILE_HOST:localhost}
    port: ${PROFILE_PORT:8082}

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}
