server:
  port: 8208
  servlet:
    context-path: /user-management

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}

application:
  aws:
    cognito:
      user-pool-id: ${COGNITO_USER_POOL_ID}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
