server:
  port: 8208
  servlet:
    context-path: /trainee-user-management

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}

application:
  aws:
    cognito:
      user-pool-id: ${COGNITO_USER_POOL_ID}
      consultation-group: ${COGNITO_CONSULTATION_GROUP:}
    sqs:
      request: ${REQUEST_QUEUE_URL:}

cloud:
  aws:
    region:
      static: ${AWS_REGION}

profile:
  server:
    name: ${PROFILE_HOST:localhost}
    port: ${PROFILE_PORT:8082}
