server:
  port: 8208
  servlet:
    context-path: /trainee-user-management

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}

application:
  aws:
    cognito:
      user-pool-id: ${COGNITO_USER_POOL_ID}
    sqs:
      profile-created: ${PROFILE_CREATED_QUEUE_URL:}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
