server:
  port: 8208
  servlet:
    context-path: /trainee-user-management

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}

application:
  aws:
    cognito:
      user-pool-id: ${COGNITO_USER_POOL_ID}
      dsp-consultant-group: ${COGNITO_DSP_CONSULTANT_GROUP}
    sqs:
      request: ${REQUEST_QUEUE_URL:}
  environment: ${ENVIRONMENT:local}

cloud:
  aws:
    region:
      static: ${AWS_REGION}

profile:
  server:
    name: ${PROFILE_HOST:localhost}
    port: ${PROFILE_PORT:8082}

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}
